### ISSUE TITLE
Don't use `Counter.Set()`

### ISSUE THREAD

**Issue by bboreham** [weaveworks/promrus#3]
Regarding [this line](https://github.com/weaveworks/promrus/blob/master/promrus.go#L25)
`Set()` was deprecated in July 2016 and removed in October 2016; please choose an alternative.

**Comment by marccarre** [comment]
I think I must have (w/o realising it was so old) configured `promrus` to use the latest release, i.e. `v0.8.0`, which still has `Set`, but I can configure it to use latest from `master` or whichever was previously in `weaveworks/notification` (`95b6848b5c5b` from Jul 12) instead.

EDIT: `v0.9.0-pre1` is much more recent  (Aug 31) and should be closer to both what is used in other projects, and the next release of the Go client.
